services:
  - type: web
    name: cosmos
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    headers:
      - path: /data/*
        name: Cache-Control
        value: "public, max-age=3600, must-revalidate"
      - path: /*.html
        name: Cache-Control
        value: "public, max-age=300, must-revalidate"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
